name: Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychEngine

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android x64
            os: macos-15
            buildArgs: "android -final -ONLY_ARM64"
            artifactName: Android x64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android x64 Build
        uses: actions/download-artifact@main
        with:
          name: Android x64
          path: /home/runner/android_x64

      - name: Move Android x64 File
        run: mv /home/runner/android_x64/*.apk /home/runner/${{ env.PROJECT_NAME }}-Android-x64.apk

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Template"
          tag_name: "0.6.3"
          last_release: false
          files: |
            /home/runner/*.apk
